SELECT Posts.POST_ID, Posts.DESCRIPTION,  Posts.CREATION_DATE, Users.USER_NAME
FROM Posts
INNER JOIN Users ON Users.USER_ID = Posts.USER_ID
GROUP BY Posts.DESCRIPTION
HAVING length(Posts.DESCRIPTION) > 5;